server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: cici
    password: 416518

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 300
        max-wait: 100
        max-idle: 16
        min-idle: 8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:/mapper/*.xml
